# Generated by Django 6.0.7 on 2026-08-05 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_kg', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('low_stock_alert', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('day_of_week', models.IntegerField()),
                ('prepared_kg', models.FloatField()),
                ('consumed_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NGOContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('quantity_per_kg', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_kg', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('cost_per_student', models.FloatField()),
                ('meal_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='food.meallog')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('dietary_pref', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.meallog')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.student')),
            ],
        ),
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('meal_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surplus', to='food.meallog')),
            ],
        ),
        migrations.CreateModel(
            name='FoodClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.student')),
                ('surplus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='food.surplusfood')),
            ],
        ),
        migrations.CreateModel(
            name='MealBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('date', models.DateField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by_admin', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='food.student')),
            ],
            options={
                'unique_together': {('student', 'meal_type', 'date')},
            },
        ),
    ]
