# Generated by Django 6.0.7 on 2026-08-06 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodclaim',
            name='claim_type',
            field=models.CharField(default='Student', max_length=20),
        ),
        migrations.AddField(
            model_name='foodclaim',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='food.ngocontact'),
        ),
        migrations.AddField(
            model_name='foodclaim',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodclaim',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.student'),
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='food.ngocontact')),
                ('surplus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.surplusfood')),
            ],
        ),
    ]
