# Generated by Django 6.0.7 on 2026-08-06 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodclaim_claim_type_foodclaim_ngo_foodclaim_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ngocontact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ngocontact',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ngocontact',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
